/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppTag: typeof import('./src/components/AppTag.vue')['default']
    AvatarList: typeof import('./src/components/AvatarList.vue')['default']
    DrawerList: typeof import('./src/components/DrawerList.vue')['default']
    ListAvatar: typeof import('./src/components/ListAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCodeLines: typeof import('./src/components/TheCodeLines.vue')['default']
  }
}
